services:
  postgres:
    image: postgres:16
    restart: always
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo2024
      POSTGRES_DB: todo